#!/bin/sh -e

VERSION=0.0.1

echo "wb $VERSION"
printf "a simple workspace manager.\n"

insta_sire() {
    read -r "Choose a language to init.
    1. C
    2. Go
    3. Shell : " sireNow

    if   [ "$sireNow" = 1 ] ; then sire_c;
    elif [ "$sireNow" = 2 ] ; then sire_go;
    elif [ "$sireNow" = 3 ] ; then sire_sh;
    else
        echo "Invalid Choice."
    fi

}

sire_c() {
    touch main.c
    echo "#include <stdio.h>" > main.c
    echo "#include <stdlib.h>" > main.c

    $EDITOR main.c
}

sire_go() {
    touch main.go
    echo "package main" > main.go

    $EDITOR main.go
}

sire_sh() {
    touch main.sh
    echo "#!/bin/sh -e" > main.sh

    $EDITOR main.sh
}

# 'read -r "bleh bleh" var' doesn't work
# low key dumb of me to keep forgetting this
# https://github.com/noirlinux/noirstrap/blob/32d5a1775ec0f65cac7d60a239d3cb97a8d517b7/repograb#L18

get_vars() {
    echo "What is the package name? : "
    read -r pkgName
    read -r "What language do you want to init?
    1. C
    2. Go
    3. Shell : " pkgLang
}

init_go() {
    mkdir -p "$pkgName"
    cd "$pkgName"
    mkdir -p cmd internal pkg docs examples assets

    echo "package main" > main.go
    git init .

    echo "Package $pkgName initialised."
}

init_c() {
    mkdir -p "$pkgName"
    cd "$pkgName"
    mkdir -p src

    touch src/Makefile.am
    touch src/main.c
    touch configure.ac
    touch Makefile.am
    touch ChangeLog

    git init .
    echo "#include <stdio.h>" > src/main.c

    echo "Package $pkgName initialised."
}

init_sh() {
    mkdir -p "$pkgName"
    cd "$pkgName"
    
    touch "$pkgName".sh
    chmod +x "$pkgName".sh
    echo "#!/bin/sh -e" > "$pkgName".sh

    touch Makefile
    git init .

    echo "Package $pkgName initialised."
}

get_vars;
#insta_sire

if   [ "$pkgLang" = 1 ] ; then init_c;
elif [ "$pkgLang" = 2 ] ; then init_go;
elif [ "$pkgLang" = 3 ] ; then init_sh;
else
    echo "You haven't made a choice."
fi 
